# Generated by Django 4.0.5 on 2022-06-28 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herois',
            fields=[
                ('idHeroi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeHeroi', models.CharField(max_length=255)),
                ('poder', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
